version: '3.4'
services:
  
  # L1BR and Laser Simulation on Gazebo (and Rviz) Nodes
  laser_l1br:
    container_name: laser_l1br
    build: .
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ros2 launch ugv_simulation l1br_laserworld.launch.py use_sim_time:=true
  
  # #SLAM Toolbox Node
  # mapping:
  #   build: .
  #   command: ros2 launch ugv_simulation online_async_launch.py slam_params_file:=xplorer_ws/install/ugv_simulation/share/ugv_simulation/config/mapper_params_online_async.yaml use_sim_time:=true
  #   env_file:
  #     - environment.env

  # # # # Navigation Node
  # navigation:
  #   build: .
  #   command: ros2 launch ugv_simulation navigation_launch.py use_sim_time:=true params_file:=xplorer_ws/src/ugv_simulation/config/nav2_params.yaml
  #   env_file:
  #     - environment.env

  # explore:
  #   # Autonomous exploration node
  #   build: .
  #   command: ros2 launch explore_lite explore.launch.py
  #   env_file:
  #     - environment.env
      
  # map-saver:
  #   build: .
  #   network_mode: host
  #   ipc: host
  #   volumes:
  #     - ./maps:/maps
  #   environment:
  #     - RMW_IMPLEMENTATION
  #   command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 360; done"